.base:
  timeout: 5 minutes
  before_script:
    - apt-get update || true
    - apt-get install -y unzip
    - apt-get install -y git
    - apt-get install -y libicu-dev
    - docker-php-ext-install intl
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer update --prefer-dist

.php81:
  image: php:8.1
  extends: .base

stages:
  - quality
  - deploy

# PHPStan

phpstan81:
  extends: .php81
  stage: quality
  except:
    - main
    - tags
  script:
    - ./vendor/bin/phpstan analyse -c phpstan.neon

# PHP code sniffer

phpcs81:
  extends: .php81
  stage: quality
  except:
    - main
    - tags
  script:
    - ./vendor/bin/phpcs --standard=./phpcs.xml

# Psalm

psalm81:
  extends: .php81
  stage: quality
  except:
    - main
    - tags
  script:
    - ./vendor/bin/psalm

# Deploy

deploy_composer:
  only:
    - tags
  stage: deploy
  script:
    - curl --data tag=${CI_COMMIT_TAG} "https://__token__:${REGISTERY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
