.base:
  timeout: 5 minutes
  before_script:
    - apt-get update || true
    - apt-get install -y unzip
    - apt-get install -y git
    - apt-get install -y libicu-dev
    - docker-php-ext-install intl
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer config gitlab-token.gitlab.com gitlab+deploy-token-713049 $REGISTERY_READ
    - composer update --prefer-dist

stages:
  - quality
  - deploy

# PHP 8.2

.php82:
  image: php:8.2
  extends: .base

phpstan82:
  extends: .php82
  stage: quality
  except:
    - main
    - tags
  script:
    - ./vendor/bin/phpstan analyse -c phpstan.neon

phpcs82:
  extends: .php82
  stage: quality
  except:
    - main
    - tags
  script:
    - ./vendor/bin/phpcs --standard=./phpcs.xml

psalm82:
  extends: .php82
  stage: quality
  except:
    - main
    - tags
  script:
    - ./vendor/bin/psalm

# PHP 8.3

.php83:
  image: php:8.3
  extends: .base

phpstan83:
  extends: .php83
  stage: quality
  except:
    - main
    - tags
  script:
    - ./vendor/bin/phpstan analyse -c phpstan.neon

phpcs83:
  extends: .php83
  stage: quality
  except:
    - main
    - tags
  script:
    - ./vendor/bin/phpcs --standard=./phpcs.xml

psalm83:
  extends: .php83
  stage: quality
  except:
    - main
    - tags
  script:
    - ./vendor/bin/psalm

# Deploy

deploy_composer:
  only:
    - tags
  stage: deploy
  script:
    - curl --data tag=${CI_COMMIT_TAG} "https://__token__:${REGISTERY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
