name: Development

on:
  push:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  composer84:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: intl
          tools: composer
      - uses: actions/checkout@v4
      - name: Cache vendor folder
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ github.sha }}-composer84
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
  phpstan84:
    runs-on: ubuntu-latest
    needs: [ composer84 ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: intl
          tools: composer
      - name: Retrieve cached vendor folder
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ github.sha }}-composer84
      - run: ./vendor/bin/phpstan analyse -c phpstan.neon --memory-limit 200M
  phpcs84:
    runs-on: ubuntu-latest
    needs: [ composer84 ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: intl
          tools: composer
      - name: Retrieve cached vendor folder
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ github.sha }}-composer84
      - run: ./vendor/bin/phpcs --standard=./phpcs.xml
#  psalm84:
#    runs-on: ubuntu-latest
#    needs: [ composer84 ]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.4'
#          extensions: intl
#          tools: composer
#      - name: Retrieve cached vendor folder
#        uses: actions/cache@v4
#        with:
#          path: vendor
#          key: ${{ github.sha }}-composer84
#      - run: ./vendor/bin/psalm
